version: "3.3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure:15
    env_file:
      - .env_db
    ports:
      - "3307:3306"
    volumes:
      - .dbdata:/var/lib/mysql
    build: .

  web:
    depends_on:
      - db
    image: shaxbozaka:latest
    restart: on-failure:15
    build: .
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - ".:/src/"


